### ISSUE TITLE
Export Private Keys in BIP32 Format

### ISSUE THREAD

**Issue by azamatms** [coinbase/multisig-tool#13]
Is there any way to export the shared key and the user key in BIP32 or "xpriv" format? Or at least get a better explanation than "Use BitcoinJS to recreate the wallet".

It should be pretty simple to just output that to the user with this tool, that way the wallet can be used with  another Bitcoin Client so we don't have to use the Vault every time to make a transaction or to withdraw instantly.

**Comment by hudon** [comment]
I think this is a great idea. We'd need a view that uses the Bip38Worker like we do in the Vault: https://github.com/coinbase/multisig-tool/blob/master/lib/multisig/vault.js#L110

**Comment by mihar** [comment]
@azamatms sounds like something we should be able to do. Feel free to take a stab at it and propose a PR.

**Comment by drewrothstein** [comment]
Closing out open issues as multisig vaults on Coinbase were deprecated on April 19, 2018.
Ref: https://blog.coinbase.com/multisig-vaults-on-coinbase-c21f58eed7cb.
This code will still be accessible at this time in an archived form.
