### ISSUE TITLE
Balance display always zero: bitcoin.toshi.io is down

### ISSUE THREAD

**Issue by tonyztan** [coinbase/multisig-tool#19]
The balance is always displayed as "0.00 BTC," because the backend API at bitcoin.toshi.io appears to be offline.

**Comment by heliodor** [comment]
Seems the latest commits to the tool have not been deployed to the website!

Look at multisig.js on the website:
```
var Bitcoin = require('bitcoinjs-lib');
var Toshi = require('./toshi');
var constants = require('./constants');
var utils = require('./utils');
```

Now look at the latest commit: https://github.com/coinbase/multisig-tool/commit/ad8fe4bf2459bb190dfbe7859c478a358f3e419d

**Comment by jimpo** [comment]
Latest version has been deployed.
