### ISSUE TITLE
Please include support for Bitcoin Cash

### ISSUE THREAD

**Issue by InternetofTrust** [coinbase/multisig-tool#26]
There's currently no way to withdraw Bitcoin Cash from Multisig Vaults using this tool. This could become a huge legal issue for Coinbase because users could get together in a class action lawsuit like it happened before when Coinbase said it wouldn't support it.

**Comment by danra** [comment]
I made a [branch](https://github.com/danra/multisig-tool/tree/bcash_extract) which adds most of the support, though unspent transactions information needs to be input manually. See the commit message in my branch for more details and disclaimers.

**Comment by drewrothstein** [comment]
Closing out open issues as multisig vaults on Coinbase were deprecated on April 19, 2018.
Ref: https://blog.coinbase.com/multisig-vaults-on-coinbase-c21f58eed7cb.
This code will still be accessible at this time in an archived form.
