### ISSUE TITLE
Hitting rate limits in HTTP API

### ISSUE THREAD

**Issue by timothybasanov** [coinbase/multisig-tool#29]
When trying to recover a wallet where I had several transactions I set a limit to 50.
Under the hood page tries to make 150 HTTP API requests to insight.bitpay.com.
One of the returned headers `x-ratelimit-limit: 30`, which implies that only 30 requests per hour could be made. Most of HTTP API requests fail due to rate limits.
Unfortunately UI does not handle failures well. There is no indication that something has failed. It just shows "0" as a total amount of money in a multisig.

Workaround:
Open JavaScript debug console and track HTTP requests to get visibility into errors.
Do not use more than 10 generated wallets.

Suggested fixes:
* Switch to a different API backend
* Add clear indication in UI that API request has failed
* Add a "retry" button to rerun all the requests so I don't have to retype all the public keys

**Comment by mihar** [comment]
This should've been resolved now!
