### ISSUE TITLE
Add Coinbase Multisig Vault data sample

### ISSUE THREAD

**Issue by Tolsi** [coinbase/multisig-tool#34]
Please provide sample data for this tool.

It will be very useful for me, thanks.

**Comment by Tolsi** [comment]
I seen the abstract format of backup data here #15

```
user seed
user public key
shared encrypted key
shared public key
coinbase public key
```
 
but the feature was removed and I can't get a sample of this backup data from the web site.

**Comment by drewrothstein** [comment]
Closing out open issues as multisig vaults on Coinbase were deprecated on April 19, 2018.
Ref: https://blog.coinbase.com/multisig-vaults-on-coinbase-c21f58eed7cb.
This code will still be accessible at this time in an archived form.
