### ISSUE TITLE
Withdrawal the vault

### ISSUE THREAD

**Issue by Andrejpogosyan** [coinbase/multisig-tool#36]
Hey there I have totally no idea how I can cash out the vault from me. I have this cryptic code which I became at the first time i logged me in. And a seed from coinbase. So If anyone can help me to cash it out I will regred this person with a part of this btc.

**Comment by drewrothstein** [comment]
Closing out open issues as multisig vaults on Coinbase were deprecated on April 19, 2018.
Ref: https://blog.coinbase.com/multisig-vaults-on-coinbase-c21f58eed7cb.
This code will still be accessible at this time in an archived form.
